export type ReadmeTemplateOptions = {
  siteKey: string;
  siteName: string;
};

export function readmeTemplate(options: ReadmeTemplateOptions) {
  return `# ${options.siteName} source

This source was generated by the onboarding CLI.

## What to update
- config.ts: selectors, product URL filters, sitemap/category URLs.
- discover.ts: verify discovery logic and pagination selectors.
- parse.ts: add site-specific selectors and parsing rules.

## Run discovery / parse / ingest
\`\`\`bash
npm run crawl -- --source=${options.siteKey} --mode=discover --limit=100
npm run crawl -- --source=${options.siteKey} --mode=parse --limit=20 --dry-run
npm run crawl -- --source=${options.siteKey} --mode=ingest --limit=20
\`\`\`

## Notes
- Respect robots.txt and the site's Terms of Service.
- Add fixtures + tests before running ingest on production data.
`;
}
